

// tag::operation-before[]


[[_upsert_db_config]]
==== Create or update a database configuration
....
PUT /{db}/_config
....



// tag::operation-begin[]


===== Description


// tag::description[]

Use this endpoint to add a new Sync Gateway databases and-or to update the configuration of an existing database.

Provide the database name in the URL path.
Provide the required database configuration settings as a JSON object in the request body.
For updates you only need to provide those settings you wish to change.

For example:

By default the created database is brought online immediately, *unless* you include `&quot;offline&quot;: true` in the configuration.

NOTE: Changes made via REST API are persisted by default.
This behavior can be changed by the command-line setting `disable_persistent_config`.

`See also: {rest-api-admin--xref}`



// end::description[]


===== Parameters


// tag::parameters[]


[options="header", cols=".^2,.^3,.^9,.^4"]
|===
|Type|Name|Description|Schema
|**Path**|**db** +
__required__|Database name|string
|**Body**|**body** +
__required__|Database Configuration Settings|<<_database-configuration,Database-configuration>>
|===



// end::parameters[]



===== Responses



// tag::responses[]


[options="header", cols=".^2,.^14,.^4"]
|===
|HTTP Code|Description|Schema
|**201**|The database configuration was created/updated successfully.|No Content
|===



// end::responses[]


===== Security


// tag::security[]



// end::security[]



// end::operation-begin[]



// end::operation-before[]



